vim.lsp.enable('arduino_language_server')
vim.lsp.enable('bashls')
vim.lsp.enable('clangd_custom')
vim.lsp.enable('cmake')
vim.lsp.enable('html')
vim.lsp.enable('lua_ls_custom')
vim.lsp.enable('markdown_oxide_custom')
vim.lsp.enable('nixd')
vim.lsp.enable('pylsp')
vim.lsp.enable('qmlls')
vim.lsp.enable('rust_analyzer')
vim.lsp.enable('tailwindcss')
vim.lsp.enable('ts_ls')
vim.lsp.enable('typos_lsp')

vim.diagnostic.config({ virtual_text = true })
